# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a4d435c5bcf1a3eb69830f9a160cc3d5d7184d340d225d4c2b8bdbfb8b041d295f5a62de53a11b010dabd2ff3454c88f9e7e8cf2b56159d20ed5dea0994a739

test:
  secret_key_base: 1be78a122384700f427dc5f8b61928f2571e54f46ddafbe36838dc7204d450443ba2c1a533d97426c1e9a7faa89f6d094ca4b3a83267bdc589b9616b26c09d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
